### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by ruddj** [hqhoang/moodle-block_massaction#5]
Good Day,
I have been receiving 2 warning messages when Mass Action has been added to a course. The block works OK, but thought I should report the warnings.

When Editing is off I receive:
    Warning: Creating default object from empty value in /moodle/htdocs/blocks/massaction/block_massaction.php on line 139

When Editing is on I receive:
    Warning: Creating default object from empty value in /moodle/htdocs/blocks/massaction/block_massaction.php on line 89

**Comment by hqhoang** [comment]
fixed in version 2013112100. Thanks.
